### ISSUE TITLE
Use `core::fmt::Write` instead of custom `StrWrite`?

### ISSUE THREAD

**Issue by camelid** [pulldown-cmark/pulldown-cmark#492]
Is there a particular reason that pulldown-cmark defines its own type, [`StrWrite`](https://docs.rs/pulldown-cmark/0.8.0/pulldown_cmark/escape/trait.StrWrite.html), rather than using the built-in Rust trait [`core::fmt::Write`](https://doc.rust-lang.org/nightly/core/fmt/trait.Write.html)? Previously `core::fmt::Write`'s documentation said

> This trait should generally not be implemented by consumers of the standard library.

But in a [recent PR](https://github.com/rust-lang/rust/pull/76750), I changed it to remove that section since no one knew of a reason why it said that. Perhaps it would be good to move pulldown over to that built-in trait?

**Comment by raphlinus** [comment]
Yes, it's because Write would require an additional utf-8 check when converting the buffer to a string, while StrWrite allows us to maintain the invariant that the buffer is valid utf-8 without resorting to any unsafe code. If you look at the history you'll see some iteration on this.

**Comment by camelid** [comment]
Hmm, I don't understand: `core::fmt::Write` and `StrWrite` look almost identical.

![image](https://user-images.githubusercontent.com/37223377/95530431-b31f9a00-0992-11eb-9e7a-396772dfbc18.png)

---

![image](https://user-images.githubusercontent.com/37223377/95530611-25907a00-0993-11eb-9c20-08e65b759087.png)

**Comment by raphlinus** [comment]
`Write` is not implemented for `String`, but `StrWrite` is. What we were doing before is using the impl of `Write` for `Vec<u8>`.

**Comment by camelid** [comment]
> `Write` is not implemented for `String`, but `StrWrite` is. What we were doing before is using the impl of `Write` for `Vec<u8>`.

Hmm, I'm pretty sure `fmt::Write` is implemented for `String` ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=4e8c7b6be0ede4a6940cc3f9edb03ad4)):

```rust
use std::fmt;

fn write<W: fmt::Write>(writer: &mut W, text: &str) {
    writer.write_str(text).unwrap();
}

fn main() {
    let mut string = String::new();
    write(&mut string, "hello string!");
    println!("{}", string);
}
```

**Comment by raphlinus** [comment]
Ah, I was confusing fmt::Write and io::Write. We also want to be able to write to files, which can be done with `WriteWrapper`, but I'm not sure any similar thing exists for fmt::Write.

**Comment by camelid** [comment]
> We also want to be able to write to files (or, more generally, anything which impl's io::Write), which can be done with `WriteWrapper`, but I'm not sure any similar thing exists for fmt::Write.

Ah, okay :)

Maybe I can add a blanket impl for `fmt::Write` if the type implements `io::Write`...

**Comment by camelid** [comment]
Opened rust-lang/rust#77733.

**Comment by marcusklaas** [comment]
It seems like a good idea to reuse a core trait. If we can't have a blanket implementation of `fmt::Write` for types that implement `io::Write`, we could just repurpose `WriteWrapper` for that.

This would be a compatibility break technically, but I think it should require minimal changes to upgrade.

**Comment by raphlinus** [comment]
Yes, thinking about this now, switching to fmt::Write and adapting our own WriteWrapper seems quite workable. The blanket in Rust looks like it's not going to happen as it can break coherence. I agree that client changes would be quite minimal, so I'd be ok with the (technical) compatibility breakage.

**Comment by marcusklaas** [comment]
Cool. @camelid: if you want to do the honors, I'd be happy to merge a PR making this change.

**Comment by camelid** [comment]
Sure!

**Comment by camelid** [comment]
Hmm, this code:

```rust
impl<W> fmt::Write for WriteWrapper<W>
where
    W: fmt::Write,
{
    #[inline]
    fn write_str(&mut self, s: &str) -> fmt::Result {
        self.0.write_str(s)
    }

    #[inline]
    fn write_fmt(&mut self, args: Arguments) -> fmt::Result {
        self.0.write_fmt(args)
    }
}

impl<W: io::Write> fmt::Write for WriteWrapper<W>
where
    W: io::Write,
{
    #[inline]
    fn write_str(&mut self, s: &str) -> fmt::Result {
        match self.0.write_all(s.as_bytes()) {
            Ok(()) => Ok(()),
            Err(err) => Err(fmt::Error),
        }
    }

    #[inline]
    fn write_fmt(&mut self, args: Arguments) -> fmt::Result {
        match self.0.write_fmt(args) {
            Ok(()) => Ok(()),
            Err(err) => Err(fmt::Error),
        }
    }
}
```

Causes this error:

```
error[E0119]: conflicting implementations of trait `std::fmt::Write` for type `escape::WriteWrapper<_>`:
  --> src/escape.rs:65:1
   |
50 | / impl<W> fmt::Write for WriteWrapper<W>
51 | | where
52 | |     W: fmt::Write,
53 | | {
...  |
62 | |     }
63 | | }
   | |_- first implementation here
64 | 
65 | / impl<W: io::Write> fmt::Write for WriteWrapper<W>
66 | | where
67 | |     W: io::Write,
68 | | {
...  |
83 | |     }
84 | | }
   | |_^ conflicting implementation for `escape::WriteWrapper<_>`
```

How do I get around this?

**Comment by marcusklaas** [comment]
We should only need

```rust
impl<W> fmt::Write for WriteWrapper<W>
where
    W: io::Write,
{ .. }
```

because one wouldn't need `WriteWrapper<W>` when `W` already implements `fmt::Write`.

**Comment by camelid** [comment]
Hmm, but what about this?

```rust
use std::fmt::Write;

// ...

pub fn write_html<'a, I, W>(writer: W, iter: I) -> fmt::Result
where
    I: Iterator<Item = Event<'a>>,
    W: Write,
{
    HtmlWriter::new(iter, WriteWrapper(writer)).run()
}
```

**Comment by camelid** [comment]
Actually I think I figured it out: I just changed the requirement to `W: io::Write` (what it used to be).

**Comment by weberc2** [comment]
I would be interested in this as well. It would be really nice to be able to reuse the `escape_html` function for `std::fmt::Write` such that I could do something like:

```rust
struct EscapedHtml(CowStr);

impl Display for EscapedHtml {
    fn fmt(&self, f: &mut Formatter<'_>) -> fmt::Result {
        escape_html(f, &self.0)
    }
}
```

Which would then permit:

```rust
// ...
Code(text) => {
    write!(w, "<code>{}</code>", EscapedHtml(&text))
}
// ...
```

Note that this pattern might also be useful for the stock `html` module.
