### ISSUE TITLE
Note, important and warning blockquote

### ISSUE THREAD

**Issue by sanpii** [pulldown-cmark/pulldown-cmark#718]
Hello,

It’s a new github flavored markdown feature: https://github.com/orgs/community/discussions/16925 (still in beta).

Is it possible to add this?

Markdown:
```markdown
> [!NOTE]  
> Highlights information that users should take into account, even when skimming.

> [!IMPORTANT]  
> Crucial information necessary for users to succeed.

> [!WARNING]  
> Critical content demanding immediate user attention due to potential risks.
```

Rendered:
> [!NOTE]  
> Highlights information that users should take into account, even when skimming.

> [!IMPORTANT]  
> Crucial information necessary for users to succeed.

> [!WARNING]  
> Critical content demanding immediate user attention due to potential risks.

**Comment by Martin1887** [comment]
This looks interesting, but probably out of scope of the basic HTML renderer or this crate.

However, it seems a useful feature for the parser, though it will not be included in the 0.10 version and needs more discussion.

Thanks!

**Comment by sanpii** [comment]
This feature is now stable: https://github.blog/changelog/2023-12-14-new-markdown-extension-alerts-provide-distinctive-styling-for-significant-content/

> This looks interesting, but probably out of scope of the basic HTML renderer or this crate.

Is it possible to just add a css class to a div, with some tricks it’s possible to have a similar rendering: https://jsfiddle.net/p1ngdavk/

**Comment by Martin1887** [comment]
Thanks for the update, but I think this feature will be deferred for the 0.11 release.

**Comment by sanpii** [comment]
I'm happily surprised to see this feature implemented, thank you!

Here the complete CSS: https://jsfiddle.net/rnoLxgqb/

**Comment by ssokolow** [comment]
> I'm happily surprised to see this feature implemented, thank you!
> 
> Here the complete CSS: https://jsfiddle.net/rnoLxgqb/

Do you know what the license is on those SVGs?

I'd like to support this in the pulldown-cmark-based renderer I wrote a few years ago to render single-page documents which is likely to end up merged with something like Zola to become my new blog generator, and I'd like to bundle nice default CSS with it.

**Comment by sanpii** [comment]
> Do you know what the license is on those SVGs?

I’m not sure. I copied/pasted the SVG from github.

According to the source of the page, it’s probably

**Comment by ssokolow** [comment]
Makes sense.

`info-16.svg`, `light-bulb-16.svg`, `report-16.svg`, `alert-16.svg`, and `stop-16.svg`, respectively, from octicons appear to be matches.

Bit of a shame there's no `Other(name)` variant on `BlockQuoteKind` though. It could be useful to be able to map things like `[!BUG]` to blocks using icons like `bug-16.svg` to render custom stuff such as known-but-not-yet-diagnosed bugs in project user guides.
