### ISSUE TITLE
[fuzz result] blank list item causes spurrious split

### ISSUE THREAD

**Issue by notriddle** [pulldown-cmark/pulldown-cmark#727]
```markdown
-

-


-



-
```

Pulldown-cmark thinks there's three lists here, but commonmark.js and commonmark-hs both think there's only one. 

[spec.commonmark.org dingus](https://spec.commonmark.org/dingus/?text=-%0A%0A-%0A%0A%0A-%0A%0A%0A%0A-)

[pandoc.org try](https://pandoc.org/try/?params=%7B%22text%22%3A%22-%5Cn%5Cn-%5Cn%5Cn%5Cn-%5Cn%5Cn%5Cn%5Cn-%5Cn%22%2C%22to%22%3A%22html%22%2C%22from%22%3A%22commonmark%22%2C%22standalone%22%3Afalse%2C%22embed-resources%22%3Afalse%2C%22table-of-contents%22%3Afalse%2C%22number-sections%22%3Afalse%2C%22citeproc%22%3Afalse%2C%22html-math-method%22%3A%22plain%22%2C%22wrap%22%3A%22auto%22%2C%22highlight-style%22%3Anull%2C%22files%22%3A%7B%7D%2C%22template%22%3Anull%7D)

**Comment by raphlinus** [comment]
Out of curiosity, how did this not appear during fuzzing? It seems exactly the kind of thing fuzzing would catch.
