### ISSUE TITLE
GFM task lists are not pretty

### ISSUE THREAD

**Issue by bobhy** [pulldown-cmark/pulldown-cmark#805]
GFM task lists are hard to read and hard to improve even if you're willing to add styling.  
Sample md:
```markdown
  - [ ] todo
  - [x] done
```
generates:

```html
<ul>
<li><input disabled="" type="checkbox"/>to do</li>
<li><input disabled="\" type="checkbox" checked=""/>done</li>
</ul>
```
which renders as:
![image](https://github.com/raphlinus/pulldown-cmark/assets/1971300/ca233e05-81db-435f-8ddd-56b4b3c30709)

## Issues
* List marker characters are visible (the "discs" in front of the list item)
* The checkmark in the checkbox is hard to see against the background of the (disabled) checkbox and the contrast between the unchecked and checked checkbox is not great either.  (see below).

It's possible to suppress the list marker characters with CSS styling (e.g `list-style-type: none;`), but that requires user to do the styling external to `pulldown-cmark`.

The (lack of) contrast is a CSS problem not limited to `pulldown-cmark` generation.  Github itself produces:
![image](https://github.com/raphlinus/pulldown-cmark/assets/1971300/a1bb5dbb-f107-4477-afc0-40b0496c0cc6)
(dark theme)

Note the check mark in the checked item is barely visible and the contrast between checked and unchecked is not outstanding.

It's not possible to improve the contrast of a *disabled* checkmark input with CSS styling (both checked or unchecked).  You can change the (foreground) color of a list marker with `accent-color`, but that doesn't apply when checkbox is disabled, and there's no CSS attribute for the marker *background* color in any case.

I found various stunts attempting to improve the rendering, but they all involve a lot of CSS which has to be provided externally.

Github generated HTML (which ought to be a reference implementation) involves suppressing the list markers, then rendering the checkbox for a task item as a hanging indent on the text of the list item.

I've got some code that takes a different approach which I'll be submitting, but I wanted to get a clear statement of the  problem out there first.

**Comment by Martin1887** [comment]
This is closed as #806 has been added to the external rendering crate meta-issuel
