### ISSUE TITLE
Parser::new_with_broken_link_callback() needs documentation / example

### ISSUE THREAD

**Issue by john-cd** [pulldown-cmark/pulldown-cmark#843]
Can you provide an example of an implementation of Parser::new_with_broken_link_callback() in the docs? 

Thank you

**Comment by Martin1887** [comment]
Right, it is missing and the docs and it would be useful. Meanwhile, you can view the example of `main.rs`:

https://github.com/raphlinus/pulldown-cmark/blob/1a5e54546b40d79eec8001d4e268b436571a78bb/pulldown-cmark/src/main.rs#L33

Thanks.

**Comment by john-cd** [comment]
I ended up writing the following:
<https://github.com/john-cd/mdbook-utils/blob/main/src/parser/mod.rs>
(at the bottom)

**Comment by Martin1887** [comment]
An example was already in the `examples` directory, definitively a mdBook (#863) would provide more visibility for this kind of things: https://github.com/pulldown-cmark/pulldown-cmark/blob/master/pulldown-cmark/examples/broken-link-callbacks.rs
