### ISSUE TITLE
Pulldown-cmark mdBook

### ISSUE THREAD

**Issue by Martin1887** [pulldown-cmark/pulldown-cmark#863]
The crate documentation of docs.rs is good for learning the API, but some things like examples and specs are difficult to find for end users, and a mdBook would improve a lot the user experience for these types of things.

**Comment by elijah-potter** [comment]
As someone currently using `pulldown_cmark` as a library, I personally haven't encountered any noticeable lack of documentation. What is an example of this?

**Comment by Martin1887** [comment]
I mean docs.rs is good for the API and a basic usage, but a book could provide a 'Getting started' chapter, and collecting examples currently only available in the code repository (https://github.com/pulldown-cmark/pulldown-cmark/tree/master/pulldown-cmark/examples).

Furthermore, the full specs could be easily checked (and with a great search engine!) instead of being only in the code repository and it could be also a good place for developers documentation, which is currently almost missing.
