### ISSUE TITLE
Tasklists with nameless checkboxes move checkbox to next paragraph

### ISSUE THREAD

**Issue by BenjaminRi** [pulldown-cmark/pulldown-cmark#882]
Suppose you have the following markdown code, which contains a nameless checkbox:

```md
* [ ] 
---
bar
```

So, we run:

```sh
printf '* [ ] \n---\nbar' | cargo run -- --enable-tasklists
```

This results in:

```html
<ul>
<li></li>
</ul>
<hr />
<p><input disabled="" type="checkbox"/>
bar</p>
```

Which looks like a stray checkbox after the horizontal rule:

![markdown_tasklist_stray_checkbox](https://github.com/pulldown-cmark/pulldown-cmark/assets/28017860/727b0307-c70f-4edf-952a-5be802c5d241)

The checkbox was erroneously added to the next paragraph element.

Additionally, if there is no paragraph following, the checkboxes disappear completely:

```sh
printf '* [ ] \n* [ ] \n* [ ] \n' | cargo run -- --enable-tasklists
```

```html
<ul>
<li></li>
<li></li>
<li></li>
</ul>
```

It seems to me like this behavior was introduced after #557 was fixed.

**Comment by Martin1887** [comment]
Sorry for the delay in the response.

This seems a very rare use case, but worthy to be solved.

Thanks!
