### ISSUE TITLE
Math: single `=` creates heading in HTML

### ISSUE THREAD

**Issue by Schabolon** [pulldown-cmark/pulldown-cmark#884]
Hi,

I have been using the `brach_0.11` with `Options::ENABLE_MATH` with the following Markdown:
```markdown
Test
$$
A
=
B
$$
```
I get the following HTML:  (but I am not sure, if this is an actual bug, or the actual expected behavior)
```html
<h1>Test
$$
A</h1>
<p>B
$$</p>
```

I would have expected to get:
```html
<p>Test
<span class="math math-display">
A
=
B
</span></p>
```

**Comment by ollpu** [comment]
Thanks for the report!

I went into detail about this in the "Display Is Inline" section when thinking about the spec: https://github.com/pulldown-cmark/pulldown-cmark/pull/733

TL:DR, unfortunately this is the intended behavior. It's a tradeoff for supporting \$\$ display math inside paragraphs/inline.

**Comment by ollpu** [comment]
Either way I guess there should be a warning about this in some documentation. Maybe the book once we get it set up.

**Comment by Schabolon** [comment]
Thanks a lot for your quick response.
I think for me personally, it would be enough, if there was a warning in the documentation.
For me, it was easy enough to fix by just reformatting to `$$A=B$$` and I would consider these niche cases.
