### ISSUE TITLE
Blockquote tags markup gets parsed in a confusingly strict way that renders it incompatible with autoformatting

### ISSUE THREAD

**Issue by ssokolow** [pulldown-cmark/pulldown-cmark#890]
[Prettier](https://prettier.io/) is a popular code formatter (more or less *the* Markdown formatter) which takes a "they're wrong, not us" attitude toward being an opinionated (i.e. minimally configurable) formatter.

(eg. They refuse to accept Doxygen applying semantic distinctions to different valid Markdown syntax for the same concept so long as Doxygen continues to read it from files with the standard `.md` extension.)

Because it doesn't recognize GFM-style admonition syntax, it's currently impossible to produce admonition markup that pulldown-cmark will recognize if using something like the gVim/Neovim [ALE](https://github.com/dense-analysis/ale) plugin to run on-save formatting of Markdown using Prettier.

## Example 1

What the user types (which, might I add, runs counter to my intution about when to add blank lines):

```markdown
> [!NOTE]
> Note
```

What Prettier (or really any admonition-unaware Markdown formatter) converts it to:

```markdown
> [!NOTE] Note
```

What pulldown-cmark interprets it as:

```
TRACE Start(BlockQuote(None))
WARN Broken link of type Shortcut: !NOTE at offset 13688
TRACE Start(Paragraph)
TRACE Start(Link { link_type: ShortcutUnknown, dest_url: Borrowed(":BROKEN_LINK:"), title: Borrowed(""), id: Borrowed("!NOTE") })
TRACE Text(Borrowed("!NOTE"))
TRACE End(Link)
TRACE Text(Borrowed(" Note"))
TRACE End(Paragraph)
TRACE End(BlockQuote)
```

(Please excuse the transformations from my frontend. The `:BROKEN_LINK:` is an unfinished bit of code that will become a workaround for #635)

## Example 2

What the user types:

```markdown
> [!NOTE]
>
> Note
```

What Prettier allows through:

```markdown
> [!NOTE]
>
> Note
```

What pulldown-cmark interprets it as:

```
TRACE Start(BlockQuote(Some(Note)))
TRACE End(BlockQuote)
TRACE Start(BlockQuote(None))
TRACE Start(Paragraph)
TRACE Text(Borrowed("Note"))
TRACE End(Paragraph)
TRACE End(BlockQuote)
```

Parsing this as two `BlockQuote` elements rather than one, despite the `>` on the whitespace between them is surprising, a footgun, and, as demonstrated, incompatible with admonition-unaware formatters.

At the moment, I'm deciding whether to leave admonition support off and wait for a bugfix from pulldown-cmark or just burn the time to implement an iterator adapter which collapses `Start(BlockQuote(Some(x))), End(BlockQuote), Start(BlockQuote(None))` into `Start(BlockQuote(Some(x)))` in the token stream.

**Comment by ssokolow** [comment]
I decided to write the iterator adapter:

```rust
/// An iterator adapter to collapse together the incorrectly split BlockQuote elements produced by
/// pulldown-cmark when using blockquote type tags/admonitions.
pub struct FixPulldownCmarkIssue890<'a, T: Iterator> {
    inner: std::iter::Peekable<T>,
    buffer: Vec<Option<Event<'a>>>,
}
impl<'a, T> FixPulldownCmarkIssue890<'a, T>
where
    T: Iterator<Item = Event<'a>>,
{
    pub fn new(iterator: T) -> Self {
        Self { inner: iterator.peekable(), buffer: Vec::new() }
    }
}

impl<'a, T> Iterator for FixPulldownCmarkIssue890<'a, T>
where
    T: Iterator<Item = Event<'a>>,
{
    type Item = Event<'a>;

    fn next(&mut self) -> Option<Self::Item> {
        loop {
            match (self.inner.peek(), self.buffer.as_slice()) {
                // If we see 3 after accumulating 1&2, drop 2&3 and return 1.
                (
                    Some(Event::Start(Tag::BlockQuote(None))),
                    [Some(Event::Start(Tag::BlockQuote(Some(_)))), Some(Event::End(TagEnd::BlockQuote))],
                ) => {
                    let _ = self.inner.next();
                    let e = self.buffer.swap_remove(0);
                    self.buffer.clear();
                    return e;
                },
                // If we see 2 and we've accumulated 1, buffer it and go around again
                (
                    Some(Event::End(TagEnd::BlockQuote)),
                    [Some(Event::Start(Tag::BlockQuote(Some(_))))],
                ) => {
                    self.buffer.push(self.inner.next());
                },
                // If we see 1 and the buffer is empty, buffer it and go around again
                (Some(Event::Start(Tag::BlockQuote(Some(_)))), []) => {
                    self.buffer.push(self.inner.next());
                },
                // Otherwise, if the buffer is empty, just pass it through
                (_, []) => return self.inner.next(),
                // Otherwise, drain the buffer
                (_, [_, ..]) => return self.buffer.pop().expect("buffer not empty"),
            }
        }
    }
}
```

**Comment by Martin1887** [comment]
I think this is out of scope because that syntax is different to GitHub's specification.

Probably an issue should be open in the formatters instead.

**Comment by ssokolow** [comment]
I'm going to leave my fix in place. Even when there's no formatter and it's a human, that element of syntactic strictness makes it a "cover the world in leather instead of buying shoes" (Buddhist idiom) solution akin to someone putting gratuitous Undefined Behaviour into a C spec revision and justifying it as "get better programmers".

I'd much rather patch one repo than billions of humans.

Lightweight markup formats like Markdown and reStructuredText are already bad enough when it comes to having trial-and-error-required properties when you're trying to typeset outline lists.

**Comment by ssokolow** [comment]
@Martin1887 

> I think this is out of scope because that syntax is different to GitHub's specification.
>
> Probably an issue should be open in the formatters instead.

While I was making preparations to file a bug with GitHub to ask them to change the specification to accept the whitespace use more in line with CommonMark's design philosophy, I discovered that https://github.github.com/gfm/ doesn't mention admonition syntax.

Which specification were you referring to?

**Comment by Martin1887** [comment]
I cannot find it, it seems that the support in GFM is not documented apart from https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts.

However, you can check other specifications like [commonmark-hs](https://pandoc.org/try/?params=%7B%22text%22%3A%22%3E+%5B%21NOTE%5D+%5Cn%3E+Content%5Cn%5Cn%3E%5Cn%3E+%5B%21NOTE%5D+%5Cn%3E+Content%5Cn%5Cn%5Cn%3E+%5C%5C%5B%21NOTE%5D+%5Cn%3E+Content%5Cn%5Cn%22%2C%22to%22%3A%22html5%22%2C%22from%22%3A%22gfm%22%2C%22standalone%22%3Afalse%2C%22embed-resources%22%3Afalse%2C%22table-of-contents%22%3Afalse%2C%22number-sections%22%3Afalse%2C%22citeproc%22%3Afalse%2C%22html-math-method%22%3A%22plain%22%2C%22wrap%22%3A%22auto%22%2C%22highlight-style%22%3Anull%2C%22files%22%3A%7B%7D%2C%22template%22%3Anull%7D).

**Comment by ssokolow** [comment]
Ugh. Well, given that GitHub is still the reference implementation, I suppose I can still poke them to support and document a "The admonition header looks like a separate paragraph, so it should be typable as a separate paragraph" adjustment to their parser.

As a UI/UX guy, I find the idea of letting this design wart ossify into a *de facto* standard to be mildly offensive.

**Comment by ssokolow** [comment]
Just a note based on something I noticed in the feature request I opened on mdBook: This change would be consistent with how GitHub itself implements GFM.

```markdown
> [!NOTE]
>
> Lorem ipsum
```

> [!NOTE]
>
> Lorem ipsum

(Also, I'd like to point out that formatters which recognize admonitions would probably normalize to the syntax I'm asking for, given that GitHub accepts it, it's less fragile in the face of PRs from people using other/older formatters in a format-on-save configuration, and it'd be consistent with how formatters typically normalize ATX headings.)

**Comment by Martin1887** [comment]
Not sure after re-evaluating this, if GitHub supports it probably pulldown-cmark should support it too despite the absence of a proper spec. What do you think, @ollpu, @notriddle?

**Comment by notriddle** [comment]
What are you proposing to change? All of these results seem consistent between GitHub and pulldown-cmark.

```console
% cargo run --release -- --enable-gfm
    Finished `release` profile [optimized] target(s) in 0.05s
     Running `target/release/pulldown-cmark --enable-gfm`
> [!NOTE]
>
> test

---

> [!NOTE]
> test

---

> [!NOTE] test
^D
<blockquote class="markdown-alert-note">
<p>test</p>
</blockquote>
<hr />
<blockquote class="markdown-alert-note">
<p>test</p>
</blockquote>
<hr />
<blockquote>
<p>[!NOTE] test</p>
</blockquote>
```

> [!NOTE]
>
> test

---

> [!NOTE]
> test

---

> [!NOTE] test

**Comment by Martin1887** [comment]
Sorry, I understood from the previous comments that pulldown-cmark interpreted them differently. Closing as completed then 🙂.

**Comment by ssokolow** [comment]
At one point, it did, and I'm not sure what the timeline was. For all I know, it didn't, but then GitHub thought my suggestion to be more lenient in parsing was a good idea (I do remember suggesting something to them but I can't remember if it was to relax the parser or to update the documentation), then pulldown-cmark followed along.

When I can spare a moment, I'll pull out my `FixPulldownCmarkIssue890` iterator adapter from the project I'm using pulldown-cmark in and confirm that this *is* fixed.

**Comment by ssokolow** [comment]
OK, confirmed.

I also use mdBook and I realized I was still on mdBook 0.4.x so I just upgraded to 0.5.x and let it pull an updated pulldown-cmark and it now does match GFM's parsing of admonitions.
