### ISSUE TITLE
capturing custom attributes added to code blocks?

### ISSUE THREAD

**Issue by DrGo** [pulldown-cmark/pulldown-cmark#893]
Apologies if this was asked before, but could not find a solution by googling or searching the issues.

`mdbook` adds custom attributes to code blocks after lang specifiers e.g.,
```md  
```rust, ignore
fn() {}
```
When parsing such a file, `pulldown` returns the `,ignore' fragment as part of the code block content.
```
, ignore
fn() {}
```
Is there a way to obtain the attribute string (after `,`) separately from the code block content?

Thanks,

**Comment by Martin1887** [comment]
Unfortunately, that extension is not part of CommonMark but exclusive of mdBook, so it is out of the scope of this project.

Such extensions can easily be thrown away using a post-processor, as mdBook does: (https://notriddle.github.io/pulldown-cmark/):

```rust
fn clean_codeblock_headers(event: Event<'_>) -> Event<'_> {
    match event {
        Event::Start(Tag::CodeBlock(CodeBlockKind::Fenced(ref info))) => {
            let info: String = info
                .chars()
                .map(|x| match x {
                    ' ' | '\t' => ',',
                    _ => x,
                })
                .filter(|ch| !ch.is_whitespace())
                .collect();

            Event::Start(Tag::CodeBlock(CodeBlockKind::Fenced(CowStr::from(info))))
        }
        _ => event,
    }
}
```

**Comment by ollpu** [comment]
Right, the whole info line should be included.

> When parsing such a file, pulldown returns the `,ignore' fragment as part of the code block content.

I'm unable to reproduce this. Could you provide a full example? Which version?
