### ISSUE TITLE
HTML Escaping doesn't work

### ISSUE THREAD

**Issue by DasLixou** [pulldown-cmark/pulldown-cmark#898]
I have this input:
```rs
r##"hello <script>alert()</script>"##
```
When rendering this as html and opening it, I get an alert. 

But it should be escaped

**Comment by ehuss** [comment]
Can you say more about why you think it should be escaped? Per [Raw HTML](https://spec.commonmark.org/0.31.2/#raw-html), any HTML tags can be included within commonmark.

If you want to add your own escaping for safety reasons, I would suggest adding your own filtering on the output. [ammonia](https://crates.io/crates/ammonia) is one such library, but there are other ways to sanitize.

**Comment by DasLixou** [comment]
Html.rs line 103 does something with escaping, so i thought it would do it. But thanks, I just wasn't sure if I need to do it or if pulldown does it
