### ISSUE TITLE
Invalid HTML is generated when inline HTML tags are nested

### ISSUE THREAD

**Issue by rhysd** [pulldown-cmark/pulldown-cmark#899]
## Repro

Save the following content as input.md.

```markdown
<span><span>

Foo

</span></span>
```

Then run

```sh
cargo run input.md
```

## Expected behavior

I expected the following HTML output:

```html
<span><span>
<p>Foo</p>
</span></span>
```

## Actual behavior

Actually the following broken HTML output was generated:

```html
<p><span><span></p>
<p>Foo</p>
<p></span></span></p>
```

## Events

Events emitted by the Markdown parser was:

```console
$ cargo run -- -e input.md
0..13: Start(Paragraph)
0..6: InlineHtml(Borrowed("<span>"))
6..12: InlineHtml(Borrowed("<span>"))
0..13: End(Paragraph)
14..18: Start(Paragraph)
14..17: Text(Borrowed("Foo"))
14..18: End(Paragraph)
19..34: Start(Paragraph)
19..26: InlineHtml(Borrowed("</span>"))
26..33: InlineHtml(Borrowed("</span>"))
19..34: End(Paragraph)
EOF
```

## Additional information

When removing outer `<span>`, it works as intended because the `<span>` and `</span>` lines are parsed as `HtmlBlock`.

```markdown
<span>

Foo

</span>
```

## Environment

- Rust: 1.78
- pulldown-cmark: 8713a415b04cdb0b7980a9a17c0ed0df0b36395e

**Comment by ehuss** [comment]
Although it may be confusing, this is intentional behavior in the spec. A tag on a line by itself followed by a blank line is considered an [HTML block](https://spec.commonmark.org/0.31.2/#html-blocks) (see clause 7). The bare `<span>` and `</span>` is treated as two separate block HTMLs.  When you have two `<span><span>`, that is treated as inline raw HTML. Those are treated as being within a paragraph. After the blank line, that ends the paragraph, thus causing the close tag.

**Comment by rhysd** [comment]
@ehuss Thank you for the point. I read the spec and understood that this is intended behavior.

Though I understood the parser works correctly, I wonder the HTML generator needs to be fixed not to output a broken HTML code. I believe this can be done by:

- Adding missing closing tags
- Remove closing tags without opening tags

If we apply these rules to the example above,

```html
<span><span></span></span>

Foo


```

this code is generated. Though it would not be an expected output, it is still not broken as HTML.

**Comment by ollpu** [comment]
I think cleaning up the HTML is out of scope for `pulldown-cmark`. It is very hard to do correctly, and the default HTML renderer's output is tested against the CommonMark spec.

You could use a separate library for this, such as [`html5ever`](https://github.com/servo/html5ever).

**Comment by rhysd** [comment]
I tried [ammonia](https://docs.rs/ammonia/latest/ammonia/) and it turned the broken HTML output into a valid HTML source. I'll adopt it. And I understood that this was out of scope of this crate. Thank you for the clarification.
