### ISSUE TITLE
 text with ‘  had be splited

### ISSUE THREAD

**Issue by eric-seekas** [pulldown-cmark/pulldown-cmark#906]
```rust
use pulldown_cmark::{Parser, Event, Options, Tag};
use std::io::Cursor;

fn main() {
    let markdown_text = "Rust's performance is impressive.";
    let parser = Parser::new_ext(markdown_text, Options::all());

    for event in parser {
        match event {
            Event::Text(text) => {
                println!("{}", text); // I expect "Rust's performance is impressive."
            }

            _ => {}
        }
    }
}
```

However, the result of the operation is:

```bash
Rust
'
s performance is impressive.
```

**Comment by rhysd** [comment]
I think this is a similar question to https://github.com/pulldown-cmark/pulldown-cmark/issues/146 and the answer would be by design.

**Comment by ollpu** [comment]
Yes, this is intentional (for performance reasons). If desired, you can use the [TextMergeStream](https://docs.rs/pulldown-cmark/latest/pulldown_cmark/utils/struct.TextMergeStream.html) helper to combine adjacent text events together.
