### ISSUE TITLE
Bug: No definition for `pulldown_cmark::html`.

### ISSUE THREAD

**Issue by auula** [pulldown-cmark/pulldown-cmark#918]
<img width="1070" alt="image" src="https://github.com/pulldown-cmark/pulldown-cmark/assets/38412458/30e1bb7a-93f0-4a8d-a1b4-9c3e287aaf79">

1. No definition for `pulldown_cmark::html`.
2. version: pulldown-cmark v0.11.0

**Comment by Martin1887** [comment]
You have to add the `html` feature, it is a default one but it seems you have specified not to use it.
