### ISSUE TITLE
`TextMergeWithOffsets` adds spaces in indented code blocks

### ISSUE THREAD

**Issue by jorendorff** [pulldown-cmark/pulldown-cmark#922]
`TextMergeWithOffsets` can merge text nodes that are not actually adjacent in the source document.

The default Parser parses an indented code block as a series of text events, one per line.  `TextMergeWithOffsets` merges all of these into a single event; but the text for that event is borrowed and contains the extra indentation characters in between those nodes. (These are usually spaces, but I think they could even contain `>` characters if the code block is in a block quote.)

I think this must be a bug. It's surprising and hard to work around, and I don't think `TextMergeStream` behaves this way.

 The code with the bug is [here](https://docs.rs/pulldown-cmark/latest/src/pulldown_cmark/utils.rs.html#141-143).

**Comment by ollpu** [comment]
Hm, looks like the implementation should be redone, and I'd like the API to be closer to `TextMergeStream`. Maybe `TextMergeStream` could be written in terms of the version with offsets. I'll have a look at these now.

**Comment by ollpu** [comment]
Fixed in `master`. The API is now the same as with `TextMergeStream`, so you have to do `TextMergeWithOffsets::new(Parser::new(...).into_offset_iter())`.
