### ISSUE TITLE
Blockquote with a colon panics on unwrap

### ISSUE THREAD

**Issue by Papierkorb** [pulldown-cmark/pulldown-cmark#964]
Hello, while working on a project which uses pulldown-cmark as one of its dependencies I stumbled upon a bug which panics due to a unwrap(). I'm using `pulldown-cmark` 0.12.1 on Rust `1.80.1`. This bug occurs with the default feature set.

## Reproduce

The issue is if there's a blockquote line with an leading colon. There must be one blockquote line before it. The following is the smallest I could get it:

```rust
#[test]
fn test() {
    let input = r#"
> a
> :b
"#;

    pulldown_cmark::Parser::new_ext(&input, pulldown_cmark::Options::all());
}
```

Running this command results in a backtrace like this:

```
   3: core::option::unwrap_failed
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/option.rs:1985:5
   4: core::option::Option<T>::unwrap
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/option.rs:935:21
   5: pulldown_cmark::firstpass::FirstPass::pop
             at .../pulldown-cmark-0.12.1/src/firstpass.rs:1507:22
   6: pulldown_cmark::firstpass::FirstPass::run
             at .../pulldown-cmark-0.12.1/src/firstpass.rs:79:13
   7: pulldown_cmark::firstpass::run_first_pass
             at .../pulldown-cmark-0.12.1/src/firstpass.rs:41:5
   8: pulldown_cmark::parse::Parser<F>::new_with_broken_link_callback
             at .../pulldown-cmark-0.12.1/src/parse.rs:247:34
   9: pulldown_cmark::parse::Parser::new_ext
             at .../pulldown-cmark-0.12.1/src/parse.rs:232:9
```

---

I'm not sure what the affected Markdown feature/syntax is called, so please apologize if this issue is already known!
Cheers

**Comment by rhysd** [comment]
I could confirm that this issue is already fixed on HEAD.

- `v0.12.1` tag (65c5159) reproduced this issue
- HEAD (3abe8ca04211fe603a2f2bfa3d5231a241b180c3) didn't reproduce this issue

The next version should fix this issue.

**Comment by rhysd** [comment]
@Martin1887 Can we have a new release?
